# Add all Industry to database.
Industry.find_or_create_by(name: "Academic")
Industry.find_or_create_by(name: "Accounting & Finance")
Industry.find_or_create_by(name: "Agriculture & Forestry")
Industry.find_or_create_by(name: "Anatomy & Physiology")
Industry.find_or_create_by(name: "Anthropology")
Industry.find_or_create_by(name: "Archaeology")
Industry.find_or_create_by(name: "Architecture & Built")
Industry.find_or_create_by(name: "Area Studies")
Industry.find_or_create_by(name: "Art & Design")
Industry.find_or_create_by(name: "Astronomy")
Industry.find_or_create_by(name: "Biological Sciences")
Industry.find_or_create_by(name: "Business & Management Studies")
Industry.find_or_create_by(name: "Chemistry")
Industry.find_or_create_by(name: "Classics & Ancient History")
Industry.find_or_create_by(name: "Communication & Media Studies")
Industry.find_or_create_by(name: "Computer Science & Info Systems")
Industry.find_or_create_by(name: "Dentistry")
Industry.find_or_create_by(name: "Development Studies")
Industry.find_or_create_by(name: "Earth Sciences")
Industry.find_or_create_by(name: "Economics & Econometrics")
Industry.find_or_create_by(name: "Education Social")
Industry.find_or_create_by(name: "Engineering")
Industry.find_or_create_by(name: "English Language & Literature")
Industry.find_or_create_by(name: "Environmental Sciences")
Industry.find_or_create_by(name: "European studies")
Industry.find_or_create_by(name: "Food Science & Technology")
Industry.find_or_create_by(name: "Genetics & Biotechnology")
Industry.find_or_create_by(name: "Geography")
Industry.find_or_create_by(name: "History")
Industry.find_or_create_by(name: "Hospitality & Leisure Management")
Industry.find_or_create_by(name: "International Affairs")
Industry.find_or_create_by(name: "Law")
Industry.find_or_create_by(name: "Library & Information Management")
Industry.find_or_create_by(name: "Linguistics")
Industry.find_or_create_by(name: "Marine Sciences")
Industry.find_or_create_by(name: "Environment Marketing")
Industry.find_or_create_by(name: "Materials Science")
Industry.find_or_create_by(name: "Mathematics")
Industry.find_or_create_by(name: "Medicine")
Industry.find_or_create_by(name: "Modern Languages")
Industry.find_or_create_by(name: "Music")
Industry.find_or_create_by(name: "Nursing")
Industry.find_or_create_by(name: "Performing Arts")
Industry.find_or_create_by(name: "Pharmacology")
Industry.find_or_create_by(name: "Pharmacy")
Industry.find_or_create_by(name: "Philosophy")
Industry.find_or_create_by(name: "Physics")
Industry.find_or_create_by(name: "Politics")
Industry.find_or_create_by(name: "Psychology")
Industry.find_or_create_by(name: "Policy & Administration")
Industry.find_or_create_by(name: "Social Work")
Industry.find_or_create_by(name: "Sociology")
Industry.find_or_create_by(name: "Sports-related Subjects")
Industry.find_or_create_by(name: "Statistics & Operational Research")
Industry.find_or_create_by(name: "Theology, Divinity & Religious Studies")
Industry.find_or_create_by(name: "Veterinary Science")
Industry.find_or_create_by(name: "Any Discipline")
Industry.find_or_create_by(name: "Other")
