# frozen_string_literal: true

# Add all Industry to database.
Industry.find_or_create_by(name: 'Agriculture, Forestry, Fishing and Animal Husbandry')
Industry.find_or_create_by(name: 'Mining and Quarrying')
Industry.find_or_create_by(name: 'Manufacturing')
Industry.find_or_create_by(name: 'Electricity and Gas Supply')
Industry.find_or_create_by(name: 'Water Supply and Remediation Activities')
Industry.find_or_create_by(name: 'Construction')
Industry.find_or_create_by(name: 'Wholesale and Retail Trade')
Industry.find_or_create_by(name: 'Transportation and Storage')
Industry.find_or_create_by(name: 'Accommodation and Food Service Activities')
Industry.find_or_create_by(name: 'Information and Communication')
Industry.find_or_create_by(name: 'Financial and Insurance Activities')
Industry.find_or_create_by(name: 'Real Estate Activities')
Industry.find_or_create_by(name: 'Professional, Scientific and Technical Activities')
Industry.find_or_create_by(name: 'Support Service Activities')
Industry.find_or_create_by(name: 'Public Administration and Defence')
Industry.find_or_create_by(name: 'Education')
Industry.find_or_create_by(name: 'Human Health and Social Work Activities')
Industry.find_or_create_by(name: 'Arts, Entertainment and Recreation')
Industry.find_or_create_by(name: 'Other Service Activities')
