version: '3.4'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      RAILS_SERVE_STATIC_FILES: "yes"
      DATABASE_URL: "mysql2://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}"
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
      AUTO_MIGRATION: "yes"
