# Add all countries to database.
Country.find_or_create_by(name: 'Afghanistan')
Country.find_or_create_by(name: 'Aland Islands')
Country.find_or_create_by(name: 'Albania')
Country.find_or_create_by(name: 'Algeria')
Country.find_or_create_by(name: 'American Samoa')
Country.find_or_create_by(name: 'Andorra')
Country.find_or_create_by(name: 'Angola')
Country.find_or_create_by(name: 'Anguilla')
Country.find_or_create_by(name: 'Antarctica')
Country.find_or_create_by(name: 'Antigua and Barbuda')
Country.find_or_create_by(name: 'Argentina')
Country.find_or_create_by(name: 'Armenia')
Country.find_or_create_by(name: 'Aruba')
Country.find_or_create_by(name: 'Australia')
Country.find_or_create_by(name: 'Austria')
Country.find_or_create_by(name: 'Azerbaijan')
Country.find_or_create_by(name: 'Bahamas')
Country.find_or_create_by(name: 'Bahrain')
Country.find_or_create_by(name: 'Bangladesh')
Country.find_or_create_by(name: 'Barbados')
Country.find_or_create_by(name: 'Belarus')
Country.find_or_create_by(name: 'Belgium')
Country.find_or_create_by(name: 'Belize')
Country.find_or_create_by(name: 'Benin')
Country.find_or_create_by(name: 'Bermuda')
Country.find_or_create_by(name: 'Bhutan')
Country.find_or_create_by(name: 'Bolivia')
Country.find_or_create_by(name: 'Bonaire, Sint Eustatius and Saba')
Country.find_or_create_by(name: 'Bosnia and Herzegovina')
Country.find_or_create_by(name: 'Botswana')
Country.find_or_create_by(name: 'Bouvet Island')
Country.find_or_create_by(name: 'Brazil')
Country.find_or_create_by(name: 'British Indian Ocean Territory')
Country.find_or_create_by(name: 'Brunei Darussalam')
Country.find_or_create_by(name: 'Bulgaria')
Country.find_or_create_by(name: 'Burkina Faso')
Country.find_or_create_by(name: 'Burundi')
Country.find_or_create_by(name: 'Cambodia')
Country.find_or_create_by(name: 'Cameroon')
Country.find_or_create_by(name: 'Canada')
Country.find_or_create_by(name: 'Cape Verde')
Country.find_or_create_by(name: 'Cayman Islands')
Country.find_or_create_by(name: 'Central African Republic')
Country.find_or_create_by(name: 'Chad')
Country.find_or_create_by(name: 'Chile')
Country.find_or_create_by(name: 'China')
Country.find_or_create_by(name: 'Christmas Island')
Country.find_or_create_by(name: 'Cocos (Keeling) Islands')
Country.find_or_create_by(name: 'Colombia')
Country.find_or_create_by(name: 'Comoros')
Country.find_or_create_by(name: 'Congo')
Country.find_or_create_by(name: 'Congo, Democratic Republic of the Congo')
Country.find_or_create_by(name: 'Cook Islands')
Country.find_or_create_by(name: 'Costa Rica')
Country.find_or_create_by(name: 'Cote D\'Ivoire')
Country.find_or_create_by(name: 'Croatia')
Country.find_or_create_by(name: 'Cuba')
Country.find_or_create_by(name: 'Curacao')
Country.find_or_create_by(name: 'Cyprus')
Country.find_or_create_by(name: 'Czech Republic')
Country.find_or_create_by(name: 'Denmark')
Country.find_or_create_by(name: 'Djibouti')
Country.find_or_create_by(name: 'Dominica')
Country.find_or_create_by(name: 'Dominican Republic')
Country.find_or_create_by(name: 'Ecuador')
Country.find_or_create_by(name: 'Egypt')
Country.find_or_create_by(name: 'El Salvador')
Country.find_or_create_by(name: 'Equatorial Guinea')
Country.find_or_create_by(name: 'Eritrea')
Country.find_or_create_by(name: 'Estonia')
Country.find_or_create_by(name: 'Ethiopia')
Country.find_or_create_by(name: 'Falkland Islands (Malvinas)')
Country.find_or_create_by(name: 'Faroe Islands')
Country.find_or_create_by(name: 'Fiji')
Country.find_or_create_by(name: 'Finland')
Country.find_or_create_by(name: 'France')
Country.find_or_create_by(name: 'French Guiana')
Country.find_or_create_by(name: 'French Polynesia')
Country.find_or_create_by(name: 'French Southern Territories')
Country.find_or_create_by(name: 'Gabon')
Country.find_or_create_by(name: 'Gambia')
Country.find_or_create_by(name: 'Georgia')
Country.find_or_create_by(name: 'Germany')
Country.find_or_create_by(name: 'Ghana')
Country.find_or_create_by(name: 'Gibraltar')
Country.find_or_create_by(name: 'Greece')
Country.find_or_create_by(name: 'Greenland')
Country.find_or_create_by(name: 'Grenada')
Country.find_or_create_by(name: 'Guadeloupe')
Country.find_or_create_by(name: 'Guam')
Country.find_or_create_by(name: 'Guatemala')
Country.find_or_create_by(name: 'Guernsey')
Country.find_or_create_by(name: 'Guinea')
Country.find_or_create_by(name: 'Guinea-Bissau')
Country.find_or_create_by(name: 'Guyana')
Country.find_or_create_by(name: 'Haiti')
Country.find_or_create_by(name: 'Heard Island and Mcdonald Islands')
Country.find_or_create_by(name: 'Holy See (Vatican City State)')
Country.find_or_create_by(name: 'Honduras')
Country.find_or_create_by(name: 'Hong Kong')
Country.find_or_create_by(name: 'Hungary')
Country.find_or_create_by(name: 'Iceland')
Country.find_or_create_by(name: 'India')
Country.find_or_create_by(name: 'Indonesia')
Country.find_or_create_by(name: 'Iran, Islamic Republic of')
Country.find_or_create_by(name: 'Iraq')
Country.find_or_create_by(name: 'Ireland')
Country.find_or_create_by(name: 'Isle of Man')
Country.find_or_create_by(name: 'Israel')
Country.find_or_create_by(name: 'Italy')
Country.find_or_create_by(name: 'Jamaica')
Country.find_or_create_by(name: 'Japan')
Country.find_or_create_by(name: 'Jersey')
Country.find_or_create_by(name: 'Jordan')
Country.find_or_create_by(name: 'Kazakhstan')
Country.find_or_create_by(name: 'Kenya')
Country.find_or_create_by(name: 'Kiribati')
Country.find_or_create_by(name: 'Korea, Democratic People\'s Republic of')
Country.find_or_create_by(name: 'Korea, Republic of')
Country.find_or_create_by(name: 'Kosovo')
Country.find_or_create_by(name: 'Kuwait')
Country.find_or_create_by(name: 'Kyrgyzstan')
Country.find_or_create_by(name: 'Lao People\'s Democratic Republic')
Country.find_or_create_by(name: 'Latvia')
Country.find_or_create_by(name: 'Lebanon')
Country.find_or_create_by(name: 'Lesotho')
Country.find_or_create_by(name: 'Liberia')
Country.find_or_create_by(name: 'Libyan Arab Jamahiriya')
Country.find_or_create_by(name: 'Liechtenstein')
Country.find_or_create_by(name: 'Lithuania')
Country.find_or_create_by(name: 'Luxembourg')
Country.find_or_create_by(name: 'Macao')
Country.find_or_create_by(name: 'Macedonia, the Former Yugoslav Republic of')
Country.find_or_create_by(name: 'Madagascar')
Country.find_or_create_by(name: 'Malawi')
Country.find_or_create_by(name: 'Malaysia')
Country.find_or_create_by(name: 'Maldives')
Country.find_or_create_by(name: 'Mali')
Country.find_or_create_by(name: 'Malta')
Country.find_or_create_by(name: 'Marshall Islands')
Country.find_or_create_by(name: 'Martinique')
Country.find_or_create_by(name: 'Mauritania')
Country.find_or_create_by(name: 'Mauritius')
Country.find_or_create_by(name: 'Mayotte')
Country.find_or_create_by(name: 'Mexico')
Country.find_or_create_by(name: 'Micronesia, Federated States of')
Country.find_or_create_by(name: 'Moldova, Republic of')
Country.find_or_create_by(name: 'Monaco')
Country.find_or_create_by(name: 'Mongolia')
Country.find_or_create_by(name: 'Montenegro')
Country.find_or_create_by(name: 'Montserrat')
Country.find_or_create_by(name: 'Morocco')
Country.find_or_create_by(name: 'Mozambique')
Country.find_or_create_by(name: 'Myanmar')
Country.find_or_create_by(name: 'Namibia')
Country.find_or_create_by(name: 'Nauru')
Country.find_or_create_by(name: 'Nepal')
Country.find_or_create_by(name: 'Netherlands')
Country.find_or_create_by(name: 'Netherlands Antilles')
Country.find_or_create_by(name: 'New Caledonia')
Country.find_or_create_by(name: 'New Zealand')
Country.find_or_create_by(name: 'Nicaragua')
Country.find_or_create_by(name: 'Niger')
Country.find_or_create_by(name: 'Nigeria')
Country.find_or_create_by(name: 'Niue')
Country.find_or_create_by(name: 'Norfolk Island')
Country.find_or_create_by(name: 'Northern Mariana Islands')
Country.find_or_create_by(name: 'Norway')
Country.find_or_create_by(name: 'Oman')
Country.find_or_create_by(name: 'Pakistan')
Country.find_or_create_by(name: 'Palau')
Country.find_or_create_by(name: 'Palestinian Territory, Occupied')
Country.find_or_create_by(name: 'Panama')
Country.find_or_create_by(name: 'Papua New Guinea')
Country.find_or_create_by(name: 'Paraguay')
Country.find_or_create_by(name: 'Peru')
Country.find_or_create_by(name: 'Philippines')
Country.find_or_create_by(name: 'Pitcairn')
Country.find_or_create_by(name: 'Poland')
Country.find_or_create_by(name: 'Portugal')
Country.find_or_create_by(name: 'Puerto Rico')
Country.find_or_create_by(name: 'Qatar')
Country.find_or_create_by(name: 'Reunion')
Country.find_or_create_by(name: 'Romania')
Country.find_or_create_by(name: 'Russian Federation')
Country.find_or_create_by(name: 'Rwanda')
Country.find_or_create_by(name: 'Saint Barthelemy')
Country.find_or_create_by(name: 'Saint Helena')
Country.find_or_create_by(name: 'Saint Kitts and Nevis')
Country.find_or_create_by(name: 'Saint Lucia')
Country.find_or_create_by(name: 'Saint Martin')
Country.find_or_create_by(name: 'Saint Pierre and Miquelon')
Country.find_or_create_by(name: 'Saint Vincent and the Grenadines')
Country.find_or_create_by(name: 'Samoa')
Country.find_or_create_by(name: 'San Marino')
Country.find_or_create_by(name: 'Sao Tome and Principe')
Country.find_or_create_by(name: 'Saudi Arabia')
Country.find_or_create_by(name: 'Senegal')
Country.find_or_create_by(name: 'Serbia')
Country.find_or_create_by(name: 'Serbia and Montenegro')
Country.find_or_create_by(name: 'Seychelles')
Country.find_or_create_by(name: 'Sierra Leone')
Country.find_or_create_by(name: 'Singapore')
Country.find_or_create_by(name: 'Sint Maarten')
Country.find_or_create_by(name: 'Slovakia')
Country.find_or_create_by(name: 'Slovenia')
Country.find_or_create_by(name: 'Solomon Islands')
Country.find_or_create_by(name: 'Somalia')
Country.find_or_create_by(name: 'South Africa')
Country.find_or_create_by(name: 'South Georgia and the South Sandwich Islands')
Country.find_or_create_by(name: 'South Sudan')
Country.find_or_create_by(name: 'Spain')
Country.find_or_create_by(name: 'Sri Lanka')
Country.find_or_create_by(name: 'Sudan')
Country.find_or_create_by(name: 'Suriname')
Country.find_or_create_by(name: 'Svalbard and Jan Mayen')
Country.find_or_create_by(name: 'Swaziland')
Country.find_or_create_by(name: 'Sweden')
Country.find_or_create_by(name: 'Switzerland')
Country.find_or_create_by(name: 'Syrian Arab Republic')
Country.find_or_create_by(name: 'Taiwan, Province of China')
Country.find_or_create_by(name: 'Tajikistan')
Country.find_or_create_by(name: 'Tanzania, United Republic of')
Country.find_or_create_by(name: 'Thailand')
Country.find_or_create_by(name: 'Timor-Leste')
Country.find_or_create_by(name: 'Togo')
Country.find_or_create_by(name: 'Tokelau')
Country.find_or_create_by(name: 'Tonga')
Country.find_or_create_by(name: 'Trinidad and Tobago')
Country.find_or_create_by(name: 'Tunisia')
Country.find_or_create_by(name: 'Turkey')
Country.find_or_create_by(name: 'Turkmenistan')
Country.find_or_create_by(name: 'Turks and Caicos Islands')
Country.find_or_create_by(name: 'Tuvalu')
Country.find_or_create_by(name: 'Uganda')
Country.find_or_create_by(name: 'Ukraine')
Country.find_or_create_by(name: 'United Arab Emirates')
Country.find_or_create_by(name: 'United Kingdom')
Country.find_or_create_by(name: 'United States')
Country.find_or_create_by(name: 'United States Minor Outlying Islands')
Country.find_or_create_by(name: 'Uruguay')
Country.find_or_create_by(name: 'Uzbekistan')
Country.find_or_create_by(name: 'Vanuatu')
Country.find_or_create_by(name: 'Venezuela')
Country.find_or_create_by(name: 'Viet Nam')
Country.find_or_create_by(name: 'Virgin Islands, British')
Country.find_or_create_by(name: 'Virgin Islands, U.s.')
Country.find_or_create_by(name: 'Wallis and Futuna')
Country.find_or_create_by(name: 'Western Sahara')
Country.find_or_create_by(name: 'Yemen')
Country.find_or_create_by(name: 'Zambia')
Country.find_or_create_by(name: 'Zimbabwe')

# Add all Industry to database.
Industry.find_or_create_by(name: "學術界")
Industry.find_or_create_by(name: "電子業")
Industry.find_or_create_by(name: "軟體業")
Industry.find_or_create_by(name: "營建業")

# Add all departments in NTUST to database.
NtustDepartment.find_or_create_by(name: "營建系")
NtustDepartment.find_or_create_by(name: "電機系")
NtustDepartment.find_or_create_by(name: "應用科技學程")

# Add all Institutions to database.
Institution.find_or_create_by(name: "臺灣科技大學", country_id: Country.find_by_name("Taiwan, Province of China").id)

