name: Reuse Test Base

on:
  workflow_call:
    inputs:
      ruby-version:
        default: '3.1.2'
        type: string
      node-version:
        default: '14'
        type: string
      command:
        required: true
        type: string

env:
  RAILS_ENV: test
  DATABASE_URL: "mysql2://root:@127.0.0.1/qs_survey_test"

permissions:
  contents: read

jobs:
  run-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: qs_survey_test
        ports:
          - 3306:3306
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: |
        bundle install
        yarn install

    - uses: nanasess/setup-chromedriver@v1

    - name: Prepare
      run: |
        bundle exec rake test:prepare
        bundle exec rake db:migrate

    - name: Test
      run: ${{ inputs.command }}
